apiVersion: v1
kind: Service
metadata:
  name: node-app
  namespace: node-app
  labels:
    app: node-app
spec:
  type: NodePort
  ports:
   - port: 8080
     nodePort: 30900
  selector:
   app: node-app
