apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      namespace: node-app
  template:
    metadata:
      labels:
        app: postgres
        namespace: node-app
    spec:
      containers:
        - name: postgres
          image: postgres:9.6
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "250Mi"
              cpu: "250m"
          securityContext:
            readOnlyRootFilesystem: false
            runAsNonRoot: false
            #runAsUser: 10001
            #capabilities:
            #  drop:
            #    - all
            #  add:
            #    - NET_BIND_SERVICE
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-node-pv-claim
