kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-node-pv-volume
  namespace: node-app
  labels:
    type: local
    app: postgres
spec:
  storageClassName: local-storage
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/postgres-node/"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-node-pv-claim
  namespace: node-app
  labels:
    app: postgres
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
